package com.yxw1268.fyp.domain;

import static com.yxw1268.fyp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAllPropertiesEquals(Plan expected, Plan actual) {
        assertPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAllUpdatablePropertiesEquals(Plan expected, Plan actual) {
        assertPlanUpdatableFieldsEquals(expected, actual);
        assertPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAutoGeneratedPropertiesEquals(Plan expected, Plan actual) {
        assertThat(actual)
            .as("Verify Plan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanUpdatableFieldsEquals(Plan expected, Plan actual) {
        assertThat(actual)
            .as("Verify Plan relevant properties")
            .satisfies(a -> assertThat(a.getCaloriesKcal()).as("check caloriesKcal").isEqualTo(expected.getCaloriesKcal()))
            .satisfies(a ->
                assertThat(a.getProteinG()).as("check proteinG").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getProteinG())
            )
            .satisfies(a ->
                assertThat(a.getCarbsG()).as("check carbsG").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCarbsG())
            )
            .satisfies(a -> assertThat(a.getFatG()).as("check fatG").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFatG()))
            .satisfies(a -> assertThat(a.getWorkoutType()).as("check workoutType").isEqualTo(expected.getWorkoutType()))
            .satisfies(a ->
                assertThat(a.getWorkoutIntensity())
                    .as("check workoutIntensity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWorkoutIntensity())
            )
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanUpdatableRelationshipsEquals(Plan expected, Plan actual) {
        assertThat(actual)
            .as("Verify Plan relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }
}
