package com.yxw1268.fyp.web.rest;

import com.yxw1268.fyp.service.MlServiceClient;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Daily coaching insight for the logged-in user, generated by the ML service.
 */
@RestController
@RequestMapping("/api/insight")
public class InsightResource {

    private static final Logger LOG = LoggerFactory.getLogger(InsightResource.class);

    private static final String FALLBACK = "Stay consistent with your plan today. Every session counts.";

    private static final List<String> TEXT_FIELDS = List.of("workout", "workoutType", "mood", "goal");
    private static final List<String> NUMBER_FIELDS = List.of("calories", "water");
    private static final int MAX_TEXT_LENGTH = 40;

    private final MlServiceClient mlServiceClient;

    public InsightResource(MlServiceClient mlServiceClient) {
        this.mlServiceClient = mlServiceClient;
    }

    @PostMapping("")
    public Map<String, Object> generateInsight(@RequestBody(required = false) Map<String, Object> body) {
        try {
            Object insight = mlServiceClient.insight(sanitize(body)).get("insight");
            if (insight instanceof String text && !text.isBlank()) {
                return Map.of("insight", text);
            }
        } catch (Exception e) {
            LOG.warn("Insight generation failed: {}", e.getMessage());
        }
        return Map.of("insight", FALLBACK);
    }

    /**
     * These values end up inside an LLM prompt, so only forward the known fields,
     * as short single-line text or plain numbers.
     */
    private static Map<String, Object> sanitize(Map<String, Object> body) {
        Map<String, Object> clean = new HashMap<>();
        if (body == null) {
            return clean;
        }
        for (String field : TEXT_FIELDS) {
            if (body.get(field) instanceof String text) {
                String value = text.replaceAll("[^\\p{L}\\p{N} ,()_-]", " ").trim();
                if (!value.isEmpty()) {
                    clean.put(field, value.substring(0, Math.min(value.length(), MAX_TEXT_LENGTH)));
                }
            }
        }
        for (String field : NUMBER_FIELDS) {
            if (body.get(field) instanceof Number number) {
                clean.put(field, number);
            }
        }
        return clean;
    }
}
